#!/usr/bin/python3
# Webcat written in 2026 by Jacob "itsyeetsup" Haché. This program is free to modify and do whatever you want with
# as long as you credit me, see < https://yeetssite.github.io/yssl-1.0/ >.

# IMPORTS
from urllib import request # To get file contents from the user-specified URL
import traceback     # To print error traceback without raising another exception
from sys import argv # To read arguments so webcat can actually know what it's supposed to do
from sys import stdout # Because print() is gay and automatically adds newlines
from sys import exit # sometimes Python's builtin method doesn't work because the site package is a dick

# GENERAL INFO
# EXIT STATS:
# 0 - There wasn't any errors, and webcat should have did what it's supposed to.
# 1 - There was an error opening the user-specified URL.
# 2 - No URL was specified by the user.
# 3 - An unexpected/unknown error occured.
version = 1.01

# GET ARGUMENTS AND FLAGS
try: # If there's an IndexError, that probably means no URL was specified.

    url=argv[1] # Get the url from the 1st argument passed by the user. forces flags and stuff to come after 
                # but simpler to develop around.

    # Check all the arguments to see if these flags are in them:
    if '-E' in argv or '--show-ends' in argv:
        DISP_LINE_ENDS = True
    else:
        DISP_LINE_ENDS = False
    if '-T' in argv or '--show-tabs' in argv:
        REPLACE_TABS = True
    else:
        REPLACE_TABS = False

    # Show help message and exit if the URL is '--help' or '-h'
    if url == '--help' or url == '-h':
        # I know this is an absolutely vile, atrocious way to display the help message.
        # I don't care, I'm a procrastinator, I'll fix it later.
        print('WEBCAT HELP')
        print('USAGE: webcat [ URL ] [ FLAGS ]')
        print('       webcat --help')
        print('       webcat --version')

        print("\nFLAGS:")
        print("-E, --show-ends         Shows '$' at the end of each line")
        print("-T, --show-tabs         Replaces tab characters with '^I'")

        print("\nEXIT STATUS:")
        print("0        Webcat completed it's task with no errors")
        print("1        There was an error related to opening the URL")
        print("2        No URL was specified")
        print("3        There was an unknown issue running webcat")

        print('\nWebcat is like cat but for files hosted over the internet.')
        print('Webcat doesnt feature all the features that cat does, its')
        print('just a simple tool to get plain text files from a URL and')
        print('print it in your terminal.\n')

        print('webcat is not an actively developed project, use it at your')
        print("own risk. It was developed because I'm sick of Firefox and")
        print("Chrome's tendency to make it really annoying to properly")
        print("view and download plain .TXT files and isn't one of my main")
        print("projects, thus it will only be updated if needed and if I still")
        print("feel like it. ~itsyeetsup(A.K.A. mangolover1899)\n")

        print("Licensed under YSSL as a part of my website. see")
        print("< https://yeetssite.github.io/yssl-1.0/ >.")
        exit(0)

    # same as above but for '--version' or '-v'
    elif url == '--version' or url == '-v':
        print('webcat version '+str(version))
        exit(0)

    # Automatically add 'https://' to urls if not present, that way URLs like 'google.com' are still valid even if not
    # typed as 'https://google.com'.
    elif '://' not in url:
        url = str('https://'+url)

# Remember how we said if there's an IndexError that probably means no URL was specified?
except IndexError:
    print('[1;37;41mwebcat: No file URL specified[0m')
    exit(2) # Exit with a status denoting that no URL was specified.

# Whether or not webcat will write the URLs file contents to stdout
DISP_CONT = False

# Open the user-specified URL and get it's file contents
try:
    with request.urlopen(url) as file:

        # Catch 404s if no exceptions are raised by urllib
        if file.getcode() == 404:
            print('webcat: "'+url+'": (404) The requested file could not be found.')
            print('[1;30m([37mi[30m): Try checking your spelling. If the error persists, the file may have been moved or deleted.[0m')
            exit(1)

        # If the URL isn't a 404, then store it's file contents as a decoded string
        else:
            file_contents = file.read().decode('UTF-8')
            DISP_CONT = True

# Catch errors, and try to explain them in a way that can be understood by normal human beings.
except Exception as err:

    # Tell the user there was an error and print some technical info (aka the exception traceback)
    print('[1;41;37mAn exception occured while opening the URL:[49;31m\n')
    print(traceback.format_exc())
    
    # Diagnose the error and give a sane explaination to the user
    # If the URL given by the user isn't actually a URL:
    if "unknown url type" in str(err):
        print('[41;37mwebcat: "'+url+'": Not a valid URL.[0m')

    # If the URL returns a 404:
    elif "404: Not Found" in str(err):
        print('[41;37mwebcat: "'+url+'": (404) The requested file could not be found.[0m')

    # If theres any other sort of error:
    else:
        stdout.write('\r\n[41;37mwebcat: "'+url+'": There was an unknown issue opening this URL.\r\nwebcat: Please check your internet connection and try again.[49;0m\r[49;0m\n')
    # Finally, exit with an error status of 1
    exit(1)


# Write the URLs file contents to stdout
if DISP_CONT:

    # Because of options like '-E' and '-T', the contents are written line-by-line.
    for line in file_contents:

        # Replace Tab characters with '^I' if '-T' specified in user arguments.
        if REPLACE_TABS:
            printline = line.replace("\t", '^I')
        # Or don't if '-T' isn't specified
        else:
            printline = line

        # Add a '$' character at the end of each line if '-E' specified.
        if DISP_LINE_ENDS:
            printline = line.replace('\n','$\n')

        # Write the final version of the line to stdout and flush the toilet.
        stdout.write(printline)
        stdout.flush()

    # Exit without an error status
    exit(0)

# If for some reason webcat isn't told to do it't main function, it's probably an error of some sort...
else:
    # ...So exit with an error status denoting an unknown error.
    print("[1;41;37mwebcat: can't display this file for some reason...[m")
    exit(3)
